import { Schema } from 'redis-om'


export const collaboratorRedisSchema = new Schema("collaborators", {
  _id: {type: 'string'},
  phone: { type: 'string'},
  code_phone_area: { type: 'string' },
  email: { type: 'string' },
  full_name: { type: 'string' },
  detail_item: {type: 'string'}
  },
  {
    dataStructure: 'JSON'
  })



// export const collaboratorRedisSchema = new Schema("collaborators", {
//     _id: {type: 'string'},
//     phone: { type: 'string'},
//     code_phone_area: { type: 'string' },
//     email: { type: 'string' },
//     full_name: { type: 'string' },
//     permanent_address: { type: 'string' },
//     temporary_address: { type: 'string' },
//     folk: { type: 'string' },
//     religion: { type: 'string' },
//     edu_level: { type: 'string' },
//     identity_number: { type: 'string' },
//     identity_place: { type: 'string' },
//     identity_date: { type: 'string' },
//     name: { type: 'string' },
//     gender: { type: 'string' },
//     birthday: { type: 'string' },
//     month_birthday: { type: 'string' },
//     password: { type: 'string' },
//     password_default: { type: 'string' },
//     salt: { type: 'string' },
//     date_create: { type: 'string' },
//     is_active: { type: 'string' },
//     is_delete: { type: 'string' },
//     is_delete_trans: { type: 'string' },
//     avatar: { type: 'string' },
//     city: { type: 'string' },
//     district: { type: 'number[]' },
//     token: { type: 'string' },
//     remainder: { type: 'string' },
//     gift_remainder: { type: 'string' },
//     work_wallet: { type: 'string' },
//     collaborator_wallet: { type: 'string' },
//     point: { type: 'string' },
//     is_verify: { type: 'string' },
//     invite_code: { type: 'string' },
//     id_inviter: { type: 'string' },
//     is_added_gift_remainder: { type: 'string' },
//     default_address: { type: 'string' },
//     is_lock_time: { type: 'string' },
//     lock_time: { type: 'string' },
//     account_number: { type: 'string' },
//     account_name: { type: 'string' },
//     bank_name: { type: 'string' },
//     is_corporation: { type: 'string' },
//     is_identity: { type: 'string' },
//     identity_frontside: { type: 'string' },
//     identity_backside: { type: 'string' },
//     is_personal_infor: { type: 'string' },
//     personal_infor_image: { type: 'string[]' },
//     is_household_book: { type: 'string' },
//     household_book_image: { type: 'string[]' },
//     is_behaviour: { type: 'string' },
//     behaviour_image: { type: 'string[]' },
//     document_code: { type: 'string' },
//     is_document_code: { type: 'string' },
//     total_job: { type: 'string' },
//     total_discount: { type: 'string' },
//     total_net_income: { type: 'string' },
//     total_gross_income: { type: 'string' },
//     total_service_fee: { type: 'string' },
//     total_net_income_of_business: { type: 'string' },
//     percent_income: { type: 'string' },
//     total_collaborator_fee: { type: 'string' },
//     id_view: { type: 'string' },
//     ordinal_number: { type: 'string' },
//     total_star: { type: 'string' },
//     total_review: { type: 'string' },
//     is_locked: { type: 'string' },
//     date_lock: { type: 'string' },
//     is_contacted: { type: 'string' },
//     star: { type: 'string' },
//     type: { type: 'string[]' },
//     service_apply: { type: 'string[]' },
//     level: { type: 'number' },
//     client_id: { type: 'string[]' },
//     // reward_received: { type: 'object[]' },
//     id_business: { type: 'string' },
//     language: { type: 'string[]' },
//     is_auto_change_money: { type: 'boolean' },
//     desire_service: { type: 'string' },
//     status: { type: 'string' },
//     note_handle_admin: { type: 'string' },
//     // id_user_system_handle: {}
//     date_actived: {type: 'string'}
//   },
//   {
//     dataStructure: 'JSON'
//   })
