export const PERMISSION_ADMIN = [
    {
      name_api: 'Danh sách/chi tiết khách hàng',
      url_access: [
        '/admin/customer_manager/get_customer_by_type',
        '/admin/customer_manager/get_detail/:id',
      ],
      key_group_api: 'customer_manager',
      name_group_api: 'Quản lý khách hàng',
      key_api_parent: [],
      id_side_bar: 'customer',
      id_element: ['list_customer', 'detail_customer'],
    },
    {
      name_api: 'Thêm/Chỉnh sửa khách hàng',
      url_access: [
        '/admin/customer_manager/create_item',
        '/admin/customer_manager/edit_item/:id',
      ],
      key_group_api: 'customer_manager',
      name_group_api: 'Quản lý khách hàng',
      key_api_parent: ['Danh sách/chi tiết khách hàng'],
      id_side_bar: 'customer',
      id_element: ['create_customer', 'edit_customer'],
    },
    {
      name_api: 'Kích hoạt/chặn khách hàng',
      url_access: ['/admin/customer_manager/acti_item/:id'],
      key_group_api: 'customer_manager',
      name_group_api: 'Quản lý khách hàng',
      key_api_parent: ['Danh sách/chi tiết khách hàng'],
      id_side_bar: 'customer',
      id_element: ['active_customer'],
    },
    {
      name_api: 'Xoá khách hàng',
      url_access: ['/admin/customer_manager/delete/:id'],
      key_group_api: 'customer_manager',
      name_group_api: 'Quản lý khách hàng',
      key_api_parent: ['Danh sách/chi tiết khách hàng'],
      id_side_bar: 'customer',
      id_element: ['delete_customer'],
    },
    {
      name_api: 'Danh sách/chi tiết CTV',
      url_access: [
        '/admin/collaborator_manager/get_list_item',
        '/admin/collaborator_manager/get_detail',
      ],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: [],
      id_side_bar: 'collaborator',
      id_element: ['get_collaborator', 'detail_collaborator'],
    },
    {
      name_api: 'Thêm/chỉnh sửa CTV',
      url_access: [
        '/admin/collaborator_manager/create_item',
        '/admin/collaborator_manager/edit_item/:id',
      ],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: ['Danh sách/chi tiết CTV'],
      id_side_bar: 'collaborator',
      id_element: ['create_collaborator', 'edit_collaborator'],
    },
    {
      name_api: 'Xác thực CTV',
      url_access: ['/admin/collaborator_manager/acti_item/:id'],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: ['Danh sách/chi tiết CTV'],
      id_side_bar: 'collaborator',
      id_element: ['verify_collaborator'],
    },
    {
      name_api: 'Khoá CTV',
      url_access: ['/admin/collaborator_manager/lock_item/:id'],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: ['Danh sách/chi tiết CTV'],
      id_side_bar: 'collaborator',
      id_element: ['lock_unlock_collaborator'],
    },
    {
      name_api: 'Liên hệ CTV',
      url_access: ['admin/collaborator_manager/contacted_collaborator/:id'],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: ['Danh sách/chi tiết CTV'],
      id_side_bar: 'collaborator',
      id_element: ['contacted_collaborator'],
    },
    {
      name_api: 'Xoá CTV',
      url_access: ['admin/collaborator_manager/acti_item/:id'],
      key_group_api: 'collaborator_manager',
      name_group_api: 'Quản lý CTV',
      key_api_parent: ['Danh sách/chi tiết CTV'],
      id_side_bar: 'collaborator',
      id_element: ['delete_collaborator'],
    },
    {
      name_api: 'Danh sách/chi tiết đơn hàng',
      url_access: [
        '/admin/group-order-manager/get_list',
        '/admin/group-order-manager/get_list_group_order_expired',
        '/admin/group-order-manager/get_detail/:id',
        '/admin/group-order-manager/get_history_order_by_group_order/:idGroupOrder',
        '/admin/order_manager/get_list',
        '/admin/order_manager/get_detail/:id',
        '/admin/order_manager/get_order_by_customer/:id',
        '/admin/order_manager/get_order_by_group_order/:idGroupOrder',
      ],
      key_group_api: 'group_order_manager',
      name_group_api: 'Quản lý đơn hàng',
      key_api_parent: [],
      id_side_bar: 'guvi_job',
      id_element: ['get_guvi_job', 'detail_guvi_job'],
    },
    {
      name_api: 'Tạo/chỉnh sửa đơn hàng',
      url_access: [
        '/admin/group-order-manager/edit_item/:id',
        '/admin/group-order-manager/calculate_fee_group_order',
        '/admin/group-order-manager/create',
        '/admin/group-order-manager/get_service_fee',
        '/admin/group-order-manager/change_cancel_to_done',
        '/admin/group-order-manager/cancel_group_order/:idGroupOrder',
        '/admin/group-order-manager/cancel_group_order_v2/:idGroupOrder',
        '/admin/group-order-manager/add_collaborator_to_order/:idGroupOrder',
        '/admin/group-order-manager/change_collaborator/:idGroupOrder',
      ],
      key_group_api: 'group_order_manager',
      name_group_api: 'Quản lý đơn hàng',
      key_api_parent: ['Danh sách/chi tiết đơn hàng'],
      id_side_bar: 'guvi_job',
      id_element: [
        'create_guvi_job',
        'edit_guvi_job',
        'add_collaborator_guvi_job',
      ],
    },
    {
      name_api: 'Huỷ/chuyển trạng thái đơn hàng',
      url_access: [
        'admin/order_manager/change_status_order/:id',
        'admin/group-order-manager/cancel_group_order_v2/:id',
      ],
      key_group_api: 'group_order_manager',
      name_group_api: 'Quản lý đơn hàng',
      key_api_parent: ['Danh sách/chi tiết đơn hàng'],
      id_side_bar: 'guvi_job',
      id_element: [
        'change_status_order_guvi_job',
        'cancel_order_detail_guvi_job',
      ],
    },
    {
      name_api: 'Xoá đơn hàng',
      url_access: ['admin/group-order-manager/delete_group_order/:id'],
      key_group_api: 'group_order_manager',
      name_group_api: 'Quản lý đơn hàng',
      key_api_parent: ['Danh sách/chi tiết đơn hàng'],
      id_side_bar: 'guvi_job',
      id_element: ['delete_order_guvi_job'],
    },
    {
      name_api: 'Danh sách sổ quỹ CTV',
      url_access: [
        '/admin/collaborator_manager/get_list_transitions',
        '/admin/collaborator_manager/get_history_transfer',
        '/admin/collaborator_manager/get_history_remainder',
        '/admin/collaborator_manager/get_history_activity',
        '/admin/collaborator_manager/get_transition_history_activity',
      ],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: [],
      id_side_bar: 'cash_book',
      id_element: [
        'get_cash_book_collaborator',
        'detail_cash_book_collaborator',
      ],
    },
    {
      name_api: 'Tạo/chỉnh sửa lệnh nạp/rút CTV',
      url_access: [
        '/admin/collaborator_manager/top_up/:idCollaborator',
        '/admin/collaborator_manager/withdraw/:idCollaborator',
        '/admin/collaborator_manager/edit_trans/:id',
      ],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: ['Danh sách sổ quỹ CTV'],
      id_side_bar: 'cash_book',
      id_element: [
        'create_cash_book_collaborator',
        'edit_cash_book_collaborator',
        'withdraw_cash_book_collaborator',
      ],
    },
    {
      name_api: 'Duyệt/huỷ lệnh nạp/rút CTV',
      url_access: [
        '/admin/collaborator_manager/verify_trans/:id',
        '/admin/collaborator_manager/cancel_trans/:id',
      ],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: ['Danh sách sổ quỹ CTV'],
      id_side_bar: 'cash_book',
      id_element: [
        'verify_transition_cash_book_collaborator',
        'cancel_transition_cash_book_collaborator',
      ],
    },
    {
      name_api: 'Xoá lệnh nạp/rút CTV',
      url_access: [
        'admin/collaborator_manager/delete_trans/:id'
      ],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: ['Danh sách sổ quỹ CTV'],
      id_side_bar: 'cash_book',
      id_element: [
        'delete_transition_cash_book_collaborator',
      ],
    },
    {
      name_api: 'Danh sách lệnh phạt CTV',
      url_access: ['admin/punish_manager/get_list_punish'],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: [],
      id_side_bar: 'cash_book',
      id_element: ['get_punish_cash_book_collaborator'],
    },
    {
      name_api: 'Thêm/chỉnh sửa lệnh phạt CTV',
      url_access: [
        'admin/punish_manager/monetary_fine/:id',
        'admin/punish_manager/edit_punish/:id',
        'admin/punish_manager/verify_punish/:id',
        'admin/punish_manager/cancel_punish/:id',
      ],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: ['Danh sách lệnh phạt CTV'],
      id_side_bar: 'cash_book',
      id_element: [
        'create_punish_cash_book_collaborator',
        'edit_punish_cash_book_collaborator',
        'verify_punish_cash_book_collaborator',
        'cancel_punish_cash_book_collaborator',
      ],
    },
    {
      name_api: 'Xoá lệnh phạt CTV',
      url_access: ['admin/punish_manager/delete_punish/:id'],
      key_group_api: 'transition_collaborator',
      name_group_api: 'Quản lý sổ quỹ CTV',
      key_api_parent: ['Danh sách lệnh phạt CTV'],
      id_side_bar: 'cash_book',
      id_element: ['delete_punish_cash_book_collaborator'],
    },
    {
      name_api: 'Danh sách sổ quỹ KH',
      url_access: [
        '/admin/collaborator_manager/get_list_transitions',
        '/admin/collaborator_manager/get_history_transfer',
        '/admin/collaborator_manager/get_history_remainder',
        '/admin/collaborator_manager/get_history_activity',
        '/admin/collaborator_manager/get_transition_history_activity',
      ],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: [],
      id_side_bar: 'cash_book',
      id_element: ['list_transition_cash_book_customer'],
    },
    {
      name_api: 'Tạo/chỉnh sửa lệnh nạp/rút KH',
      url_access: [
        '/admin/collaborator_manager/top_up/:idCollaborator',
        '/admin/collaborator_manager/withdraw/:idCollaborator',
        '/admin/collaborator_manager/edit_trans/:id',
      ],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách sổ quỹ KH'],
      id_side_bar: 'cash_book',
      id_element: [
        'create_transition_cash_book_customer',
        'edit_transition_cash_book_customer',
      ],
    },
    {
      name_api: 'Duyệt/huỷ lệnh nạp KH',
      url_access: [
        '/admin/collaborator_manager/verify_trans/:id',
        '/admin/collaborator_manager/cancel_trans/:id',
      ],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách sổ quỹ KH'],
      id_side_bar: 'cash_book',
      id_element: [
        'verify_transition_cash_book_customer',
        'cancel_transition_cash_book_customer',
      ],
    },
    {
      name_api: 'Xoá lệnh nạp/rút KH',
      url_access: ['/admin/collaborator_customer/delete_trans/:id'],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách sổ quỹ KH'],
      id_side_bar: 'cash_book',
      id_element: ['delete_transition_cash_book_customer'],
    },
    {
      name_api: 'Danh sách điểm thưởng KH',
      url_access: [
        'admin/customer_manager/get_list_transition_point_customer',
      ],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: [],
      id_side_bar: 'cash_book',
      id_element: ['get_transition_point_cash_book_customer'],
    },
    {
      name_api: 'Tạo lệnh nạp điểm thưởng KH',
      url_access: ['admin/customer_manager/top_up_point_customer/:id'],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách điểm thưởng KH'],
      id_side_bar: 'cash_book',
      id_element: ['topup_point_cash_book_customer'],
    },
    {
      name_api: 'Duyệt/huỷ lệnh nạp điểm thưởng KH',
      url_access: [
        'admin/customer_manager/verify_point_customer/:id',
        'admin/customer_manager/cancel_point_customer/:id',
      ],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách điểm thưởng KH'],
      id_side_bar: 'cash_book',
      id_element: [
        'verify_point_cash_book_customer',
        'cancel_point_cash_book_customer',
      ],
    },
    {
      name_api: 'Xoá lệnh nạp điểm thưởng KH',
      url_access: ['admin/customer_manager/delete_point_customer/:id'],
      key_group_api: 'transition_customer',
      name_group_api: 'Quản lý sổ quỹ KH',
      key_api_parent: ['Danh sách điểm thưởng KH'],
      id_side_bar: 'cash_book',
      id_element: ['delete_point_cash_book_customer'],
    },

    {
      name_api: 'Danh sách thưởng CTV',
      url_access: [
        'admin/info_reward_collaborator/get_list',
      ],
      key_group_api: 'reward_collaborator',
      name_group_api: 'Quản lý thưởng CTV',
      key_api_parent: [],
      id_side_bar: 'cash_book',
      id_element: ['get_reward_cash_book_collaborator'],
    },
    {
      name_api: 'Duyệt/huỷ thưởng CTV',
      url_access: [
        'admin/info_reward_collaborator/verify_item/:id',
        'admin/info_reward_collaborator/cancel_item/:id'
      ],
      key_group_api: 'reward_collaborator',
      name_group_api: 'Quản lý thưởng CTV',
      key_api_parent: ['Danh sách thưởng CTV'],
      id_side_bar: 'cash_book',
      id_element: ['verify_reward_cash_book_collaborator', 'cancel_reward_cash_book_collaborator'],
    },
    {
      name_api: 'Xoá thưởng CTV',
      url_access: [
        'admin/info_reward_collaborator/delete_item/:id'
      ],
      key_group_api: 'reward_collaborator',
      name_group_api: 'Quản lý thưởng CTV',
      key_api_parent: ['Danh sách thưởng CTV'],
      id_side_bar: 'cash_book',
      id_element: ['delete_reward_cash_book_collaborator'],
    },

    {
      name_api: 'Danh sách yêu cầu',
      url_access: ['/admin/customer_request_manager/get_list'],
      key_group_api: 'request_service',
      name_group_api: 'Quản lý yêu cầu',
      key_api_parent: ['Danh sách sổ quỹ KH'],
      id_side_bar: 'request_service',
      id_element: ['list_request_service'],
    },
    {
      name_api: 'Liên hệ yêu cầu',
      url_access: [
        '/admin/customer_request_manager/delete_customer_request',
      ],
      key_group_api: 'request_service',
      name_group_api: 'Quản lý yêu cầu',
      key_api_parent: ['Danh sách yêu cầu'],
      id_side_bar: 'request_service',
      id_element: ['contact_request_service'],
    },
    {
      name_api: 'Thay đổi trạng thái yêu cầu',
      url_access: ['/admin/customer_request_manager/contact/:id'],
      key_group_api: 'request_service',
      name_group_api: 'Quản lý yêu cầu',
      key_api_parent: ['Danh sách yêu cầu'],
      id_side_bar: 'request_service',
      id_element: ['change_status_request_service'],
    },
    {
      name_api: 'Xoá yêu cầu',
      url_access: ['/admin/customer_request_manager/change_status/:id'],
      key_group_api: 'request_service',
      name_group_api: 'Quản lý yêu cầu',
      key_api_parent: ['Danh sách yêu cầu'],
      id_side_bar: 'request_service',
      id_element: ['delete_request_service'],
    },
    {
      name_api: 'Danh sách/chi tiết khuyến mãi',
      url_access: [
        '/admin/promotion_manager/get_list',
        '/admin/promotion_manager/detail',
      ],
      key_group_api: 'promotion_manager',
      name_group_api: 'Quản lý khuyến mãi',
      key_api_parent: [],
      id_side_bar: 'promotion',
      id_element: ['get_promotion', 'detail_promotion'],
    },
    {
      name_api: 'Tạo/chỉnh sửa khuyến mãi',
      url_access: [
        '/admin/promotion_manager/create_item',
        '/admin/promotion_manager/edit_item',
      ],
      key_group_api: 'promotion_manager',
      name_group_api: 'Quản lý khuyến mãi',
      key_api_parent: ['Danh sách/chi tiết khuyến mãi'],
      id_side_bar: 'promotion',
      id_element: ['create_promotion', 'edit_promotion'],
    },
    {
      name_api: 'Kích hoạt/ngừng kích hoạt mã khyến mãi',
      url_access: ['/admin/promotion_manager/active'],
      key_group_api: 'promotion_manager',
      name_group_api: 'Quản lý khuyến mãi',
      key_api_parent: ['Danh sách/chi tiết khuyến mãi'],
      id_side_bar: 'promotion',
      id_element: ['active_promotion'],
    },
    {
      name_api: 'Xoá khuyến mãi',
      url_access: ['/admin/promotion_manager/delete_soft'],
      key_group_api: 'promotion_manager',
      name_group_api: 'Quản lý khuyến mãi',
      key_api_parent: ['Danh sách/chi tiết khuyến mãi'],
      id_side_bar: 'promotion',
      id_element: ['delete_promotion'],
    },
    {
      name_api: 'Danh sách/chi tiết banner',
      url_access: [
        'admin/banner_manager/get_list',
        'admin/banner_manager/get_detail_item/:id',
      ],
      key_group_api: 'banner_manager',
      name_group_api: 'Quản lý banner',
      key_api_parent: [],
      id_side_bar: 'promotion',
      id_element: ['get_banner', 'detail_banner'],
    },
    {
      name_api: 'Thêm/chỉnh sửa banner',
      url_access: [
        'admin/banner_manager/create_item',
        'admin/banner_manager/edit_item/:id',
      ],
      key_group_api: 'banner_manager',
      name_group_api: 'Quản lý banner',
      key_api_parent: ['Danh sách/chi tiết banner'],
      id_side_bar: 'promotion',
      id_element: ['create_banner', 'edit_banner'],
    },
    {
      name_api: 'Ẩn/hiện sửa banner',
      url_access: ['admin/banner_manager/acti_item/:id'],
      key_group_api: 'banner_manager',
      name_group_api: 'Quản lý banner',
      key_api_parent: ['Danh sách/chi tiết banner'],
      id_side_bar: 'promotion',
      id_element: ['active_banner'],
    },
    {
      name_api: 'Xoá banner',
      url_access: ['admin/banner_manager/delete_item/:id'],
      key_group_api: 'banner_manager',
      name_group_api: 'Quản lý banner',
      key_api_parent: ['Danh sách/chi tiết banner'],
      id_side_bar: 'promotion',
      id_element: ['delete_banner'],
    },
    {
      name_api: 'Danh sách/chi tiết bài viết',
      url_access: [
        'admin/news_manager/get_list',
        'admin/news_manager/get_detail/:id',
      ],
      key_group_api: 'news_manager',
      name_group_api: 'Quản lý bài viết',
      key_api_parent: [],
      id_side_bar: 'promotion',
      id_element: ['get_news', 'detail_news'],
    },
    {
      name_api: 'Thêm/chỉnh sửa bài viết',
      url_access: [
        'admin/news_manager/create_item',
        'admin/news_manager/edit_item/:id',
      ],
      key_group_api: 'news_manager',
      name_group_api: 'Quản lý bài viết',
      key_api_parent: ['Danh sách/chi tiết bài viết'],
      id_side_bar: 'promotion',
      id_element: ['create_news', 'edit_news'],
    },
    {
      name_api: 'Ẩn/hiện bài viết',
      url_access: ['admin/news_manager/active/:id'],
      key_group_api: 'news_manager',
      name_group_api: 'Quản lý bài viết',
      key_api_parent: ['Danh sách/chi tiết bài viết'],
      id_side_bar: 'promotion',
      id_element: ['active_news'],
    },
    {
      name_api: 'Xoá bài viết',
      url_access: ['admin/news_manager/delete/:id'],
      key_group_api: 'news_manager',
      name_group_api: 'Quản lý bài viết',
      key_api_parent: ['Danh sách/chi tiết bài viết'],
      id_side_bar: 'promotion',
      id_element: ['delete_news'],
    },
    {
      name_api: 'Danh sách thông báo',
      url_access: ['/admin/push_notification_manager/get_item'],
      key_group_api: 'notification_manager',
      name_group_api: 'Quản lý thông báo',
      key_api_parent: [],
      id_side_bar: 'notification',
      id_element: ['get_notification'],
    },
    {
      name_api: 'Tạo/chỉnh sửa thông báo',
      url_access: [
        '/admin/push_notification_manager/create_item',
        '/admin/push_notification_manager/edit_item',
      ],
      key_group_api: 'notification_manager',
      name_group_api: 'Quản lý thông báo',
      key_api_parent: ['Danh sách thông báo'],
      id_side_bar: 'notification',
      id_element: ['create_notification', 'edit_notification'],
    },
    {
      name_api: 'Kích hoạt thông báo',
      url_access: ['/admin/push_notification_manager/active_item'],
      key_group_api: 'notification_manager',
      name_group_api: 'Quản lý thông báo',
      key_api_parent: ['Danh sách thông báo'],
      id_side_bar: 'notification',
      id_element: ['active_notification'],
    },
    {
      name_api: 'Xoá thông báo',
      url_access: ['/admin/push_notification_manager/delete_item'],
      key_group_api: 'notification_manager',
      name_group_api: 'Quản lý thông báo',
      key_api_parent: ['Danh sách thông báo'],
      id_side_bar: 'notification',
      id_element: ['delete_notification'],
    },

    {
      name_api: 'Báo cáo đơn hàng',
      url_access: ['/admin/group-order-manager/report_group_order'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_report'],
    },
    {
      name_api: 'Báo đơn hàng theo ngày',
      url_access: ['/admin/report_mananger/report_order_daily'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_by_daily_report'],
    },
    {
      name_api: 'Báo cáo đơn hàng theo khu vực',
      url_access: [
        'admin/report_mananger/report_percent_order_city',
        'admin/report_mananger/report_order_city',
        'admin/aministrative_division_manager/get_aministrative_division',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_by_arera_report'],
    },
    {
      name_api: 'Báo cáo đơn hàng theo khách hàng',
      url_access: ['admin/report_mananger/report_customer_old_new'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_by_customer_report'],
    },
    {
      name_api: 'Báo cáo CTV',
      url_access: ['admin/report_mananger/report_collaborator'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['collaborator_report'],
    },
    {
      name_api: 'Báo cáo CTV',
      url_access: ['admin/report_mananger/report_collaborator'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['collaborator_report'],
    },
    {
      name_api: 'Báo cáo số lượng khách hàng',
      url_access: [
        'admin/customer_manager/total_customer',
        'admin/customer_manager/total_customer_monthly/2023',
        'admin/customer_manager/total_customer_dayly',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['count_customer_report'],
    },
    {
      name_api: 'Báo cáo lượt giới thiệu',
      url_access: [
        'admin/report_mananger/report_customer_inviter',
        'admin/report_mananger/top_customer_inviter',
        'admin/report_mananger/report_customer_inviter',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['customer_invite_report'],
    },
    {
      name_api: 'Báo cáo khách hàng theo khu vực',
      url_access: ['admin/report_mananger/report_customer_by_city'],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['customer_by_area_report'],
    },
    {
      name_api: 'Báo cáo đơn huỷ',
      url_access: [
        'admin/report_mananger/report_cancel_order',
        'admin/report_mananger/report_overview_cancel_order',
        'admin/aministrative_division_manager/get_aministrative_division',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_cancel_report'],
    },
    {
      name_api: 'Báo cáo dịch vụ',
      url_access: [
        'admin/aministrative_division_manager/get_aministrative_division',
        'admin/report_mananger/report_service_by_area',
        'admin/report_mananger/report_detail_service_by_area',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_by_service_report'],
    },
    {
      name_api: 'Báo cáo tổng quan (dành riêng cho online.gov.vn)',
      url_access: [
        'admin/report_mananger/report_gov',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_by_service_report'],
    },
    {
      name_api: 'Báo cáo đơn hàng ngày trong tuần',
      url_access: [
        'admin/report_mananger/report_order_day_in_week',
      ],
      key_group_api: 'report_manager',
      name_group_api: 'Quản lý báo cáo',
      key_api_parent: [],
      id_side_bar: 'report',
      id_element: ['order_report_day_in_week'],
    },
    {
      name_api: 'Danh sách quyền quản trị',
      url_access: [
        'admin/user_system_manager/get_list_role_admin',
        'admin/user_system_manager/get_setting_key_api',
      ],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý cấu hình',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_role_permission_setting'],
    },
    {
      name_api: 'Thêm/sửa quyền quản trị',
      url_access: [
        'admin/user_system_manager/create_role_admin',
        'admin/user_system_manager/edit_role_admin/:id',
      ],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý cấu hình',
      key_api_parent: ['Danh sách quyền quản trị'],
      id_side_bar: 'setting',
      id_element: [
        'create_role_permission_setting',
        'edit_role_permission_setting',
      ],
    },

    {
      name_api: 'Thêm/sửa quyền quản trị',
      url_access: [
        'admin/user_system_manager/create_role_admin',
        'admin/user_system_manager/edit_role_admin/:id',
      ],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý cấu hình',
      key_api_parent: ['Danh sách quyền quản trị'],
      id_side_bar: 'setting',
      id_element: [
        'create_role_permission_setting',
        'edit_role_permission_setting',
      ],
    },

    {
      name_api: 'Danh sách/chi tiết tài khoản',
      url_access: [
        'admin/user_system_manager/get_list',
        'admin/user_system_manager/get_detail/:id',
      ],
      key_group_api: 'user_system_manager',
      name_group_api: 'Quản lý tài khoản quản trị',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_user_system'],
    },
    {
      name_api: 'Thêm/sửa tài khoản',
      url_access: [
        'admin/user_system_manager/create_admin',
        'admin/user_system_manager/edit_admin/:id',
      ],
      key_group_api: 'user_system_manager',
      name_group_api: 'Quản lý tài khoản quản trị',
      key_api_parent: ['Danh sách/chi tiết tài khoản'],
      id_side_bar: 'setting',
      id_element: ['create_user_system', 'edit_user_system'],
    },
    {
      name_api: 'Khoá/mở khoá tài khoản',
      url_access: ['admin/user_system_manager/acti_admin/:id'],
      key_group_api: 'user_system_manager',
      name_group_api: 'Quản lý tài khoản quản trị',
      key_api_parent: ['Danh sách/chi tiết tài khoản'],
      id_side_bar: 'setting',
      id_element: ['active_user_system'],
    },
    {
      name_api: 'Xoá tài khoản',
      url_access: ['admin/user_system_manager/delete_admin/:id'],
      key_group_api: 'user_system_manager',
      name_group_api: 'Quản lý tài khoản quản trị',
      key_api_parent: ['Danh sách/chi tiết tài khoản'],
      id_side_bar: 'setting',
      id_element: ['delete_user_system'],
    },
    {
      name_api: 'Danh sách/chi tiết lý do huỷ',
      url_access: [
        'admin/reason_cancel_manager/get_list',
        'admin/reason_cancel_manager/detail_item/:id',
      ],
      key_group_api: 'setting_reason_manager',
      name_group_api: 'Cấu hình lý do huỷ',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_reason_cancel_setting'],
    },
    {
      name_api: 'Thêm/sửa lý do huỷ',
      url_access: [
        'admin/reason_cancel_manager/create_item',
        'admin/reason_cancel_manager/edit_item/:id',
      ],
      key_group_api: 'setting_reason_manager',
      name_group_api: 'Cấu hình lý do huỷ',
      key_api_parent: ['Danh sách/chi tiết lý do huỷ'],
      id_side_bar: 'setting',
      id_element: [
        'create_reason_cancel_setting',
        'edit_reason_cancel_setting',
      ],
    },
    {
      name_api: 'Khoá/mở lý do huỷ',
      url_access: ['admin/reason_cancel_manager/active_item/:id'],
      key_group_api: 'setting_reason_manager',
      name_group_api: 'Cấu hình lý do huỷ',
      key_api_parent: ['Danh sách/chi tiết lý do huỷ'],
      id_side_bar: 'setting',
      id_element: ['active_reason_cancel_setting'],
    },
    {
      name_api: 'Xoá lý do huỷ',
      url_access: ['admin/reason_cancel_manager/delete_item/:id'],
      key_group_api: 'setting_reason_manager',
      name_group_api: 'Cấu hình lý do huỷ',
      key_api_parent: ['Danh sách/chi tiết lý do huỷ'],
      id_side_bar: 'setting',
      id_element: ['delete_reason_cancel_setting'],
    },
    {
      name_api: 'Danh sách/chi tiết nhóm khách hàng',
      url_access: [
        'admin/group_customer_mamager/get_list',
        'admin/group_customer_mamager/get_detail/:id',
      ],
      key_group_api: 'setting_group_customer',
      name_group_api: 'Quản lý nhóm khách hàng',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_group_customer_setting'],
    },
    {
      name_api: 'Thêm/chỉnh sửa nhóm khách hàng',
      url_access: [
        'admin/group_customer_mamager/create_item',
        'dmin/group_customer_mamager/edit_item/:id',
      ],
      key_group_api: 'setting_group_customer',
      name_group_api: 'Quản lý nhóm khách hàng',
      key_api_parent: ['Danh sách/chi tiết nhóm khách hàng'],
      id_side_bar: 'setting',
      id_element: [
        'create_group_customer_setting',
        'edit_group_customer_setting',
      ],
    },
    {
      name_api: 'Khoá/mở nhóm khách hàng',
      url_access: ['admin/group_customer_mamager/acti_item/:id'],
      key_group_api: 'setting_group_customer',
      name_group_api: 'Quản lý nhóm khách hàng',
      key_api_parent: ['Danh sách/chi tiết nhóm khách hàng'],
      id_side_bar: 'setting',
      id_element: ['active_group_customer_setting'],
    },
    {
      name_api: 'Xoá nhóm khách hàng',
      url_access: ['admin/group_customer_mamager/delete_item/:id'],
      key_group_api: 'setting_group_customer',
      name_group_api: 'Quản lý nhóm khách hàng',
      key_api_parent: ['Danh sách/chi tiết nhóm khách hàng'],
      id_side_bar: 'setting',
      id_element: ['delete_group_customer_setting'],
    },
    {
      name_api: 'Cấu hình ứng dụng khách hàng',
      url_access: ['admin/setting_app_customer/get_setting'],
      key_group_api: 'setting_app_customer',
      name_group_api: 'Quản lý ứng dụng khách hàng',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_app_customer_setting'],
    },
    {
      name_api: 'Chỉnh sửa cấu hình ứng dụng khách hàng',
      url_access: ['admin/setting_app_customer/edit_setting'],
      key_group_api: 'setting_app_customer',
      name_group_api: 'Quản lý ứng dụng khách hàng',
      key_api_parent: ['Cấu hình ứng dụng khách hàng'],
      id_side_bar: 'setting',
      id_element: ['edit_app_customer_setting'],
    },
    {
      name_api: 'Cấu hình ứng dụng cộng tác viên',
      url_access: ['admin/setting_app_collaborator/get_setting'],
      key_group_api: 'setting_app_collaborator',
      name_group_api: 'Quản lý ứng dụng cộng tác viên',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_app_collaborator_setting'],
    },
    {
      name_api: 'Chỉnh sửa cấu hình ứng dụng cộng tác viên',
      url_access: ['admin/setting_app_collaborator/edit_setting'],
      key_group_api: 'setting_app_collaborator',
      name_group_api: 'Quản lý ứng dụng cộng tác viên',
      key_api_parent: ['Cấu hình ứng dụng cộng tác viên'],
      id_side_bar: 'setting',
      id_element: ['edit_app_collaborator_setting'],
    },
    {
      name_api: 'Danh sách/chi tiết bộ câu hỏi',
      url_access: [
        'admin/exam_test/get_list',
        'admin/exam_test/detail_question/:id',
      ],
      key_group_api: 'setting_exam_test',
      name_group_api: 'Quản lý bộ câu hỏi',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_exam_test_setting'],
    },
    {
      name_api: 'Thêm/chỉnh sửa câu hỏi',
      url_access: [
        'admin/exam_test/create_question',
        'admin/exam_test/edit_question/:id',
      ],
      key_group_api: 'setting_exam_test',
      name_group_api: 'Quản lý bộ câu hỏi',
      key_api_parent: ['Danh sách/chi tiết bộ câu hỏi'],
      id_side_bar: 'setting',
      id_element: ['create_exam_test_setting', 'edit_exam_test_setting'],
    },
    {
      name_api: 'Khoá/mở câu hỏi',
      url_access: ['admin/exam_test/acti_question/:id'],
      key_group_api: 'setting_exam_test',
      name_group_api: 'Quản lý bộ câu hỏi',
      key_api_parent: ['Danh sách/chi tiết bộ câu hỏi'],
      id_side_bar: 'setting',
      id_element: ['active_exam_test_setting'],
    },
    {
      name_api: 'Xoá câu hỏi',
      url_access: ['admin/exam_test/delete_question/:id'],
      key_group_api: 'setting_exam_test',
      name_group_api: 'Quản lý bộ câu hỏi',
      key_api_parent: ['Danh sách/chi tiết bộ câu hỏi'],
      id_side_bar: 'setting',
      id_element: ['delete_exam_test_setting'],
    },
    {
      name_api: 'Danh sách/chi tiết lý do phạt',
      url_access: [
        'admin/reason_punish_manager/get_list',
        'admin/reason_punish_manager/detail_item/:id',
      ],
      key_group_api: 'setting_reason_punish',
      name_group_api: 'Cấu hình lý do phạt',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_reason_punish_setting'],
    },
    {
      name_api: 'Thêm/chỉnh sửa lý do phạt',
      url_access: [
        'admin/reason_punish_manager/create_item',
        'admin/reason_punish_manager/edit_item/:id',
      ],
      key_group_api: 'setting_reason_punish',
      name_group_api: 'Cấu hình lý do phạt',
      key_api_parent: ['Danh sách/chi tiết lý do phạt'],
      id_side_bar: 'setting',
      id_element: [
        'create_reason_punish_setting',
        'edit_reason_punish_setting',
      ],
    },
    {
      name_api: 'Xoá lý do phạt',
      url_access: ['admin/reason_punish_manager/delete_item/:id'],
      key_group_api: 'setting_reason_punish',
      name_group_api: 'Cấu hình lý do phạt',
      key_api_parent: ['Danh sách/chi tiết lý do phạt'],
      id_side_bar: 'setting',
      id_element: ['delete_reason_punish_setting'],
    },
    {
      name_api: 'Danh sách/chi tiết điều kiện thưởng CTV',
      url_access: [
        'admin/reward_collaborator_manager/get_list',
        'admin/reward_collaborator_manager/detail_reward/:id',
      ],
      key_group_api: 'setting_reward_collaborator',
      name_group_api: 'Cấu hình thưởng CTV',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_reward_collaborator_setting', 'detail_reward_collaborator_setting'],
    },
    {
      name_api: 'Thêm/chỉnh sửa điều kiện thưởng CTV',
      url_access: [
        'admin/reward_collaborator_manager/create_reward',
        'admin/reward_collaborator_manager/edit_reward/:id',
      ],
      key_group_api: 'setting_reward_collaborator',
      name_group_api: 'Cấu hình thưởng CTV',
      key_api_parent: ['Danh sách/chi tiết điều kiện thưởng CTV'],
      id_side_bar: 'setting',
      id_element: ['create_reward_collaborator_setting', 'edit_reward_collaborator_setting'],
    },
    {
      name_api: 'Mở/chặn điều kiện thưởng CTV',
      url_access: [
        'admin/reward_collaborator_manager/acti_reward/:id',
      ],
      key_group_api: 'setting_reward_collaborator',
      name_group_api: 'Cấu hình thưởng CTV',
      key_api_parent: ['Danh sách/chi tiết điều kiện thưởng CTV'],
      id_side_bar: 'setting',
      id_element: ['active_reward_collaborator_setting'],
    },
    {
      name_api: 'Xoá điều kiện thưởng CTV',
      url_access: [
        'admin/reward_collaborator_manager/delete_reward/:id',
      ],
      key_group_api: 'setting_reward_collaborator',
      name_group_api: 'Cấu hình thưởng CTV',
      key_api_parent: ['Danh sách/chi tiết điều kiện thưởng CTV'],
      id_side_bar: 'setting',
      id_element: ['delete_reward_collaborator_setting'],
    },
    {
      name_api: 'Danh sách nhóm dịch vụ',
      url_access: [
        'admin/group_service_manager/get_list'
      ],
      key_group_api: 'setting_group_service',
      name_group_api: 'Cấu hình dịch vụ',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_group_service_setting'],
    },
    {
      name_api: 'Biểu đồ thống kê đơn hàng theo ngày',
      url_access: ['admin/report_mananger/total_finance_job_system'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['total_finance_job_dashboard'],
    },
    {
      name_api: 'Xem tổng các số liệu',
      url_access: ['admin/report_mananger/get_general_total_report'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['get_general_total_report_dashboard'],
    },
    {
      name_api: 'Xem xếp hạng cộng tác viên',
      url_access: ['admin/statistic/top_collaborators'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['top_collaborator_dashboard'],
    },
    {
      name_api: 'Xem tỉ lệ kết nối dịch vụ',
      url_access: ['admin/statistic/connection_service_percent'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['connection_service_dashboard'],
    },
    {
      name_api: 'Xem các đơn hàng gần nhất',
      url_access: ['admin/statistic/lastest_services'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['lastest_services_dashboard'],
    },
    {
      name_api: 'Xem lịch sử hoạt động hệ thống',
      url_access: ['admin/statistic/history_activity'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['history_activity_dashboard'],
    },
    {
      name_api: 'Xem thống kê đơn hàng theo dịch vụ',
      url_access: ['admin/report_mananger/report_detail_service_by_area'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['report_detail_service_dashboard'],
    },
    {
      name_api: 'Xem thống kê số lượng người đăng kí',
      url_access: ['admin/customer_manager/total_customer_monthly/:year'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['total_customer_monthly_dashboard'],
    },
    {
      name_api: 'Xem tổng đơn hàng bị huỷ',
      url_access: ['admin/report_mananger/report_cancel_order'],
      key_group_api: 'dashboard_manager',
      name_group_api: 'Quản lý trang tổng quan',
      key_api_parent: [],
      id_side_bar: 'dashboard',
      id_element: ['report_cancel_order_dashboard'],
    },
    {
      name_api: 'Danh sách đánh giá đơn hàng',
      url_access: ['admin/report_mananger/report_review'],
      key_group_api: 'support_customer_manager',
      name_group_api: 'Quản lý chăm sóc khách hàng',
      key_api_parent: [],
      id_side_bar: 'support_customer',
      id_element: ['list_review_support_customer'],
    },
    {
      name_api: 'Xử lý đơn hàng đánh giá',
      url_access: ['admin/report_mananger/admin_check_review'],
      key_group_api: 'support_customer_manager',
      name_group_api: 'Quản lý chăm sóc khách hàng',
      key_api_parent: ['Danh sách đánh giá đơn hàng'],
      id_side_bar: 'support_customer',
      id_element: ['admin_check_review_support_customer'],
    },
    {
      name_api: 'Danh sách phản hồi khách hàng',
      url_access: ['admin/feedback_manager/get_list'],
      key_group_api: 'support_customer_manager',
      name_group_api: 'Quản lý chăm sóc khách hàng',
      key_api_parent: [],
      id_side_bar: 'support_customer',
      id_element: ['list_feedback_support_customer'],
    },
    {
      name_api: 'Xoá phản hồi khách hàng',
      url_access: ['admin/feedback_manager/delete_feedback/:id'],
      key_group_api: 'support_customer_manager',
      name_group_api: 'Quản lý chăm sóc khách hàng',
      key_api_parent: [],
      id_side_bar: 'support_customer',
      id_element: ['delete_feedback_support_customer'],
    },
    {
      name_api: 'Danh sách các dịch vụ',
      url_access: [
        'admin/service_manager/get_list',
        'admin/group_service_manager/get_list',
      ],
      key_group_api: 'service_manager',
      name_group_api: 'Quản lý dịch vụ',
      key_api_parent: [],
      id_side_bar: 'service',
      id_element: ['get_service'],
    },
    {
      name_api: 'Ẩn/hiện dịch vụ',
      url_access: ['admin/service_manager/active_item/:id'],
      key_group_api: 'service_manager',
      name_group_api: 'Quản lý dịch vụ',
      key_api_parent: ['Danh sách các dịch vụ'],
      id_side_bar: 'service',
      id_element: ['active_service'],
    },
    {
      name_api: 'Danh sách file',
      url_access: ['admin/file_manager/get_list'],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý file',
      key_api_parent: [],
      id_side_bar: 'service',
      id_element: ['get_file_manager'],
    },
    {
      name_api: 'Xoá file',
      url_access: ['admin/file_manager/delete_file'],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý file',
      key_api_parent: ['Danh sách file'],
      id_side_bar: 'setting',
      id_element: ['delete_file_manager'],
    },
    {
      name_api: "Quản lý dịch vụ",
      url_access: ["admin/group_service_manager/get_list"],
      key_group_api: "setting_manager",
      name_group_api: "Quản lý cấu hình",
      key_api_parent: [],
      id_side_bar: "setting",
      id_element: ["get_group_service_setting"]
    },
    {
      name_api: 'Xem báo cáo tài chính',
      url_access: [
        'admin/report_mananger/report_detail_balance_customer',
        'admin/report_mananger/report_detail_balance_collaborator',
        'admin/report_mananger/report_balance',
      ],
      key_group_api: 'finance_manager',
      name_group_api: 'Quản lý tài chính',
      key_api_parent: [],
      id_side_bar: 'finance',
      id_element: ['finance_page'],
    },
    {
      name_api: 'Quản lý nhóm khuyến mãi',
      url_access: ['admin/group_promotion_manager/get_list'],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý cấu hình',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_group_promotion_setting'],
    },
    {
      name_api: 'Quản lý đối tác',
      url_access: ['admin/group_promotion_manager/get_list'],
      key_group_api: 'setting_manager',
      name_group_api: 'Quản lý cấu hình',
      key_api_parent: [],
      id_side_bar: 'setting',
      id_element: ['get_business_setting'],
    }
  ];