export * from './address.dto'
export * from './admin.dto'
export * from './banner.dto'
export * from './collaborator.dto'
export * from './customer.dto'
export * from './customerRequest.dto'
export * from './extendOptional.dto'
export * from './function.dto'
export * from './general.dto'
export * from './groupCustomer.dto'
export * from './groupService.dto'
export * from './infoRewardCollaborator.dto'
export * from './news.dto'
export * from './notification-schedule.dto'
export * from './optionalService.dto'
export * from './order.dto'
export * from './policyManage.dto'
export * from './promotion.dto'
export * from './rewardTicket.dto'
export * from './service.dto'
export * from './statistic.dto'
export * from './transitionCollaborator.dto'
export * from './transitionCustomer.dto'



